module.exports = {
  MONGODB_URI: process.env.MONGODB_URI, 
  COOKIE_SECRET: process.env.COOKIE_SECRET, 
  CLOUDINARY_CONFIG: process.env.CLOUDINARY_CONFIG, 
  KEYSTONE_ADMIN_USERNAME: process.env.ADMIN_USERNAME,
  KEYSTONE_ADMIN_PASSWORD: process.env.ADMIN_PASSWORD, 
  NEWRELIC_LICENSE_KEY: process.env.NEW_RELIC_LICENSE_KEY,
  SHOPIFY_HOST: process.env.SHOPIFY_HOST,
}